domains:
- domain: pastafariancalendar.com
  type: PRIMARY
- domain: www.pastafariancalendar.com
  type: ALIAS
name: pastafarian
region: nyc
services:
- environment_slug: node-js
  github:
    branch: main
    deploy_on_push: true
    repo: mjradwin/pastafarian
  name: pastafarian
  http_port: 8080
  instance_count: 1
  instance_size_slug: basic-xxs
  routes:
  - path: /
  run_command: npm run start
  source_dir: /
